### PR TITLE
refactor: refactored logic to verify palindrome

### PR DESCRIPTION
**Pull request by kamtoeddy**

### CODE REVIEW

**Review by lindzfaith — COMMENTED** [review]
Although this code is short and simplified, the palindrome checker was created for the Javascript certificate on freeCodeCamps. For that, you have to remove all punctuation and spacing meaning that this code will not work for those tests.

**Comment by kamtoeddy** [comment]
> Although this code is short and simplified, the palindrome checker was created for the Javascript certificate on freeCodeCamps. For that, you have to remove all punctuation and spacing meaning that this code will not work for those tests.

Hi,
That sounds like a challenge. Can I have a few examples so I can improve the code?

**Comment by lindzfaith** [comment]
> > Although this code is short and simplified, the palindrome checker was created for the Javascript certificate on freeCodeCamps. For that, you have to remove all punctuation and spacing meaning that this code will not work for those tests.
> 
> Hi, That sounds like a challenge. Can I have a few examples so I can improve the code?

Here are some examples of what should return true:
"eye"
"A man, a plan, a canal. Panama"
"never odd or even"

And here are some that should return false:
"1 eye for of 1 eye."
"not a palindrome"

Here is the link to the certificate:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/palindrome-checker

**Comment by kamtoeddy** [comment]
Thanks

**Comment by kamtoeddy** [comment]
I have updated the code

**Pull request closed without merging**
